version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
    container_name: tototodo-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
    ports:
      - 8000:8000
  
  ui:
    build:
      context: .
      dockerfile: ./docker/frontend.dockerfile
    volumes:
    - ./frontend:/app
    depends_on:
      - web
    container_name: tototodo-ui
    ports:
      - 8001:8080

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tototodo
    container_name: tototodo-db
    ports:
      - 33066:3306

volumes:
  tototodo-data:
