version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    environment: /tmp/test-results

    steps:
      - checkout
      
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Install Docker client
          command: |
            sudo apt-get update && sudo apt-get install docker

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update && sudo apt-get install docker-compose

      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Run backend tests
          working_directory: ./backend
          command: |
            go install github.com/cucumber/godog/cmd/godog@v0.12.0 &&
            if command -v godog &> /dev/null; then godog 2>/dev/null ; fi

      - setup_remote_docker

      - run:
          name: Run frontend tests
          working_directory: ./backend
          command: npm run test:e2e

      - setup_remote_docker

      - run:
          name: Start
          command: docker-compose up -d

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  deploy:
    executor: gcp-cli/default
    steps:
      - gcp-cli/install
      - gcp-cli/initialize
      
      - run:
          name: deploy service
          command: |
            export cmd='sudo docker stop $(docker ps -a -q) || true && sudo docker rm $(docker ps -a -q) || true && docker image prune -a -f || true && docker run -d -p 80:5000'
            gcloud --quiet compute ssh  "$GCE_INSTANCE_NAME" --tunnel-through-iap --command="$cmd $IMAGE_NAME"
