version: 2

jobs:
  build:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    working_directory: /go/src/github.com/circleci/cci-demo-docker

    environment: /tmp/test-results

    steps:
      - checkout

      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk --no-cache add curl
            pip install wget
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run: echo "Initializing build with docker stack"
      - run: docker swarm init
      - run: docker stack deploy -c stackfile.yml bitroid
      - run: sleep 90
      - run: docker service ps bitroid_app
      - run: docker service ls
      - run: docker ps -a

      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Run backend tests
          command: |
            (cd backend && godog)

      - setup_remote_docker

      - run:
          name: Run frontend tests
          command: |
            (cd frontend && npm run test:e2e)

      - setup_remote_docker

      - run:
          name: Start
          command: docker-compose up

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results