version: 2

jobs:
  build:

    environment: /tmp/test-results

    steps:
      - checkout

      - run:
          name: Install Docker client
          command: |
            sudo apt-get update && sudo apt-get install docker

      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update && sudo apt-get install docker-compose

      - run:
          name: Run Docker Daemon
          command: |
            sudo dockerd

      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Run backend tests
          command: |
            (cd backend && godog)

      - setup_remote_docker

      - run:
          name: Run frontend tests
          command: |
            (cd frontend && npm run test:e2e)

      - setup_remote_docker

      - run:
          name: Start
          command: docker-compose up

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results